### ISSUE TITLE
Please resolve this error

### ISSUE THREAD

**Issue by gharryh** [tstaerk/adaptivethumb#5]
As i am a simple user i dont know how to resolve this error, no other than removing the require line from the localsettings.php . This is the error:
Warning: require_once(/home/harry-arends.nl/public_html/mat54_Wiki/extensions/AdaptiveThumb/AdaptiveThumb.php): failed to open stream: No such file or directory in /home/harry-arends.nl/public_html/mat54_Wiki/LocalSettings.php on line 308

Fatal error: require_once(): Failed opening required '/home/harry-arends.nl/public_html/mat54_Wiki/extensions/AdaptiveThumb/AdaptiveThumb.php' (include_path='/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/pear_exception:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/console_getopt:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/pear-core-minimal/src:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/mail_mime:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/mail_mime-decode:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/net_socket:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/net_smtp:/home/harry-arends.nl/public_html/mat54_Wiki/vendor/pear/mail:.:/usr/share/php') in /home/harry-arends.nl/public_html/mat54_Wiki/LocalSettings.php on line 308

Regards

Harry

**Comment by tstaerk** [comment]
Nice. I am requiring this file because I was assuming everybody had a full-blown mediawiki installation. Will look into this.

**Comment by gharryh** [comment]
Hi

 

Wat do you mean with a full-blown installation??

 

Van: Thorsten Staerk [mailto:notifications@github.com] 
Verzonden: zondag 19 februari 2017 14:10
Aan: tstaerk/adaptivethumb
CC: gharryh; Author
Onderwerp: Re: [tstaerk/adaptivethumb] Please resolve this error (#5)

 

Nice. I am requiring this file because I was assuming everybody had a full-blown mediawiki installation. Will look into this.

**Comment by JensSteckhan** [comment]
I had a similar issue. My problem was that the extension path was lower case: adaptivethumb/adaptivethumb.php, but the path in LocalSettings.php was camel case.
Once I matched them, everything worked fine for me.

**Comment by tstaerk** [comment]
please state where you see these error messages
